dist: xenial

language: node_js

node_js:
  - node
  - 14

env:
  global:
    - COVERALLS_SERVICE_NAME=travis-pro
    - COVERALLS_REPO_TOKEN=YT53lAbINN4drLFtqMe4ZaP6uwEhVsOMf
    - COVERALLS_GIT_BRANCH=main
    - COVERALLS_PARALLEL=true

services:
  - docker

before_install: docker build -t midtrans/client .

script: docker image ls

os:
  - linux

notifications:
  webhooks: https://coveralls.io/webhook?repo_token=YT53lAbINN4drLFtqMe4ZaP6uwEhVsOMf
  email: restuwahyu13@mail.com
